import assert from "node:assert/strict"
import path from "node:path"
import { Cause, Effect, Exit } from "effect"
import { Database } from "../src/database/database"
import { AppNodeBuilder } from "../src/effect/app-node-builder"
import { LayerNode } from "../src/effect/layer-node"
import { Global } from "../src/global"
import { Location } from "../src/location"
import { ModelV2 } from "../src/model"
import { ProContract } from "../src/pro-contract"
import { ProContractOpenCode } from "../src/pro-contract/open-code"
import { ProContractPolicy } from "../src/pro-contract/policy"
import { ProContractPromotion } from "../src/pro-contract/promotion"
import { ProviderV2 } from "../src/provider"
import { AbsolutePath } from "../src/schema"
import { Snapshot } from "../src/snapshot"
import { Hash } from "../src/util/hash"

const seed = { version: 1, solver: "initial solver", generator: "initial generator" } as const
const candidate = { version: 1, solver: "qualified solver", generator: "qualified generator" } as const
const sibling = { version: 1, solver: "branch solver", generator: "branch generator" } as const
const scope = "fresh-process-policy"
const protocol: ProContractPromotion.Protocol = {
  version: 1,
  performanceRule: "task-pareto",
  evaluatorHash: Hash.sha256("frozen local adversarial fixture evaluator"),
  tests: [
    { id: "safety", total: 1 },
    ...(["development", "confirmation"] as const).flatMap((panel) =>
      ["0", "1"].map((replicate) => ({
        id: `${panel}-${replicate}`,
        total: 100,
        performance: { panel, task: "task", replicate },
      })),
    ),
  ],
}

function evidence(bundle: ProContractPolicy.Bundle, full = true): ProContractPromotion.Evidence {
  return {
    protocolHash: ProContractPromotion.hashProtocol(protocol),
    candidateHash: ProContractPolicy.hashBundle(bundle),
    baselineHash: ProContractPolicy.hashBundle(seed),
    receiptHash: Hash.sha256("frozen local complete report"),
    rows: protocol.tests.map((row) => ({
      id: row.id,
      total: row.total,
      passed: row.id === "safety" ? 1 : row.performance?.panel === "development" && full ? 100 : 60,
      valid: true,
    })),
    baseline: protocol.tests.map((row) => ({
      id: row.id,
      total: row.total,
      passed: row.id === "safety" ? 1 : 50,
      valid: true,
    })),
  }
}

const propose = Effect.fnUntraced(function* (project: string, bundle: ProContractPolicy.Bundle, revision: number) {
  const policies = yield* ProContractPolicy.Service
  const contracts = yield* ProContract.Service
  const bindings = yield* ProContractOpenCode.Service
  const snapshots = yield* Snapshot.Service
  const bound = yield* policies.bind({ scope, role: "generator" })
  yield* Effect.promise(() => Bun.write(path.join(project, "strategy.json"), JSON.stringify(bundle)))
  const subjectHash = yield* snapshots.capture()
  assert(subjectHash)
  const id = ProContract.ID.create()
  const issued = yield* bindings.issue({
    id,
    scope: "generation",
    spec: { ...ProContract.defaultSpec("Produce frozen strategy.json", 0), requires: [bound.requirement] },
    location: { directory: AbsolutePath.make(project) },
    model: ModelV2.Ref.make({ providerID: ProviderV2.ID.make("fixture"), id: ModelV2.ID.make("no-provider") }),
    executionPolicy: bound.executionPolicy,
    now: 0,
  })
  assert.equal(issued.decision.type, "accepted")
  assert.equal((yield* contracts.activate(id, 1, 0)).decision.type, "accepted")
  const execution = yield* bindings.claim(id, 0)
  assert(execution)
  assert(yield* bindings.reserveTurn(execution.sessionID, 1))
  assert.equal(
    (yield* contracts.reportReady({
      contractID: id,
      revision: 1,
      subjectHash,
      summary: "Exact generated bytes",
      uncertainties: [],
      time: 2,
    })).decision.type,
    "accepted",
  )
  return yield* policies.propose({
    scope,
    expectedRevision: revision,
    bundle,
    generation: { contractID: id, revision: 1, subjectHash },
    now: 3,
  })
})

const observe = Effect.gen(function* () {
  const policies = yield* ProContractPolicy.Service
  const contracts = yield* ProContract.Service
  const state = yield* policies.get(scope)
  assert(state)
  const support = yield* Effect.forEach(state.history, (item) =>
    Effect.gen(function* () {
      const contract = yield* contracts.get(item.contractID)
      return {
        contract,
        attestation: contract?.attestationID ? yield* contracts.getAttestation(contract.attestationID) : undefined,
        history: yield* contracts.history({ contractID: item.contractID }),
      }
    }),
  )
  return { state, support, quiet: yield* contracts.quiet(scope) }
})

export type Observation = Effect.Success<typeof observe>

if (import.meta.main) {
  const [stage, directory, contractID] = process.argv.slice(2)
  assert(stage && directory)
  const project = path.join(directory, "project")
  const result = await Effect.runPromise(
    Effect.gen(function* () {
      const policies = yield* ProContractPolicy.Service
      const contracts = yield* ProContract.Service

      if (stage === "promote" || stage === "race-seed") {
        yield* policies.authorize({ scope, protocol, bundle: seed, now: 0 })
        const first = yield* propose(project, candidate, 1)
        if (stage === "race-seed") {
          const second = yield* propose(project, sibling, 1)
          return { proposals: [first.id, second.id], ...(yield* observe) }
        }
        const settled = yield* policies.settle({ contractID: first.id, evidence: evidence(candidate), now: 4 })
        assert(settled.decision.eligible)
        assert.equal(settled.state.selected, 1)
        assert.deepEqual(settled.state.retainedFull, ["development:task"])
        return yield* observe
      }

      if (stage === "observe") return yield* observe

      if (stage === "withdraw") {
        const before = yield* observe
        const selected = before.state.history[before.state.selected]
        const retried = yield* policies.settle({
          contractID: selected.contractID,
          evidence: evidence(candidate),
          now: 99,
        })
        assert.deepEqual(retried.state, before.state)
        assert.deepEqual(yield* observe, before)
        const conflict = yield* policies
          .settle({
            contractID: selected.contractID,
            evidence: { ...evidence(candidate), receiptHash: Hash.sha256("changed retry") },
            now: 100,
          })
          .pipe(Effect.exit)
        assert(Exit.isFailure(conflict))
        assert.match(Cause.pretty(conflict.cause), /Conflicting policy settlement retry/)
        assert.deepEqual(yield* observe, before)

        yield* policies.revoke({
          scope,
          expectedRevision: 2,
          evidenceHash: Hash.sha256("withdraw qualified support"),
          now: 101,
        })
        const revoked = yield* observe
        const unavailable = yield* policies.bind({ scope, role: "solver" }).pipe(Effect.exit)
        assert(Exit.isFailure(unavailable))
        assert.match(Cause.pretty(unavailable.cause), /support was withdrawn/)
        // Exact authorization retries must not restore the seed or erase revocation.
        assert.deepEqual(yield* policies.authorize({ scope, protocol, bundle: seed, now: 102 }), revoked.state)
        assert.deepEqual(yield* observe, revoked)
        yield* policies.rollback({ scope, expectedRevision: 3, now: 103 })
        return yield* observe
      }

      if (stage === "withdrawn-retry") {
        const before = yield* observe
        assert.equal(before.state.revision, 4)
        assert.equal(before.state.selected, 0)
        assert.equal((yield* policies.bind({ scope, role: "solver" })).executionPolicy, seed.solver)
        const historical = yield* policies.settle({
          contractID: before.state.history[1].contractID,
          evidence: evidence(candidate),
          now: 200,
        })
        assert(historical.decision.eligible)
        assert.equal(historical.contract.status, "escalated")
        assert.deepEqual(yield* observe, before)
        const stale = yield* policies.rollback({ scope, expectedRevision: 3, now: 201 }).pipe(Effect.exit)
        assert(Exit.isFailure(stale))
        assert.match(Cause.pretty(stale.cause), /Stale policy selection revision/)
        assert.deepEqual(yield* observe, before)
        const readmission = yield* propose(project, candidate, 4).pipe(Effect.exit)
        assert(Exit.isFailure(readmission))
        assert.match(Cause.pretty(readmission.cause), /separately authorized frozen scope/)
        assert.deepEqual((yield* observe).state, before.state)
        return yield* observe
      }

      if (stage === "retained-full") {
        const proposal = yield* propose(project, sibling, 4)
        const settled = yield* policies.settle({
          contractID: proposal.id,
          evidence: evidence(sibling, false),
          now: 300,
        })
        assert.deepEqual(settled.decision.regressed, [])
        assert.deepEqual(settled.decision.improved, ["development:task", "confirmation:task"])
        assert.deepEqual(settled.decision.lostFull, ["development:task"])
        assert.equal(settled.decision.eligible, false)
        assert.equal(settled.contract.status, "escalated")
        assert.equal(settled.state.selected, 0)
        return yield* observe
      }

      assert(stage === "race-first" || stage === "race-second")
      assert(contractID)
      const settled = yield* policies
        .settle({
          contractID: ProContract.ID.make(contractID),
          evidence: evidence(stage === "race-first" ? candidate : sibling),
          now: 4,
        })
        .pipe(Effect.exit)
      return {
        accepted: Exit.isSuccess(settled),
        error: Exit.isFailure(settled) ? Cause.pretty(settled.cause) : undefined,
        contract: yield* contracts.get(ProContract.ID.make(contractID)),
        ...(yield* observe),
      }
    }).pipe(
      Effect.provide(
        AppNodeBuilder.build(
          LayerNode.group([ProContractPolicy.node, ProContract.node, ProContractOpenCode.node, Snapshot.node]),
          [
            [Database.node, Database.layerFromPath(path.join(directory, "policy.db"))],
            [Location.node, Location.boundNode(Location.Ref.make({ directory: AbsolutePath.make(project) }))],
            [
              Global.node,
              Global.layerWith({ data: directory, config: path.join(directory, "config"), cache: directory }),
            ],
          ],
        ),
      ),
    ),
  )
  console.log(JSON.stringify({ pid: process.pid, ...result }))
}
